### ISSUE TITLE
Server crash on start 1.16.1

### ISSUE THREAD

**Issue by NDR445** [Globox1997/EquipZ#2]

**Comment by Globox1997** [comment]
could you send me the crash report?

**Comment by NDR445** [comment]
It doesnt generate any, i dont know if this helps but here is what the cmd shows:
![Anotación 2020-06-29 084549](https://user-images.githubusercontent.com/62239031/85982227-beebdf80-b9e5-11ea-9f06-17201f1b4360.png)

**Comment by Globox1997** [comment]
Working on it

**Comment by Globox1997** [comment]
fixed it
